# docker-compose.yml
services:
  app:
    build: ./e-commerce
    volumes:
      - ./e-commerce:/e-commerce
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db